"""add datasources and mockup fields

Revision ID: 25eae6a18650
Revises: 
Create Date: 2026-07-10 08:13:54.540904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eae6a18650'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Integer(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasources_id'), 'datasources', ['id'], unique=False)
    op.create_index(op.f('ix_datasources_name'), 'datasources', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_file_name', sa.String(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('file_pdf_path', sa.String(), nullable=True),
    sa.Column('file_ppt_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('include_ai_insights', sa.Boolean(), nullable=True),
    sa.Column('include_raw_data_summary', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('sla_met', sa.Boolean(), nullable=True),
    sa.Column('processing_time_sec', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_datasources_name'), table_name='datasources')
    op.drop_index(op.f('ix_datasources_id'), table_name='datasources')
    op.drop_table('datasources')
    # ### end Alembic commands ###
