"""add_user_profile_and_report_threat_counters

Revision ID: 3dc939d132cc
Revises: 25eae6a18650
Create Date: 2026-07-15 13:28:06.914227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc939d132cc'
down_revision: Union[str, None] = '25eae6a18650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('threat_count_critical', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('threat_count_high', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('threat_count_medium', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('threat_count_low', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('total_records_parsed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    op.drop_column('reports', 'total_records_parsed')
    op.drop_column('reports', 'threat_count_low')
    op.drop_column('reports', 'threat_count_medium')
    op.drop_column('reports', 'threat_count_high')
    op.drop_column('reports', 'threat_count_critical')
    # ### end Alembic commands ###
