"""add_user_profile_and_report_threat_counters

Revision ID: 8575f702a969
Revises: 3dc939d132cc
Create Date: 2026-07-15 13:31:55.463635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8575f702a969'
down_revision: Union[str, None] = '3dc939d132cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
