"""add threat_count_info column

Revision ID: 9b5ac6fe9a4a
Revises: b387a98e7c25
Create Date: 2026-07-21 16:03:53.905581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5ac6fe9a4a'
down_revision: Union[str, None] = 'b387a98e7c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('threat_count_info', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'threat_count_info')
    # ### end Alembic commands ###
