"""add tokens_generated column

Revision ID: a82afa3f5122
Revises: bd1a5ef568d9
Create Date: 2026-07-25 17:49:51.992987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82afa3f5122'
down_revision: Union[str, None] = 'bd1a5ef568d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('tokens_generated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'tokens_generated')
    # ### end Alembic commands ###
