"""add password_set column

Revision ID: b387a98e7c25
Revises: a5d517fe8bcd
Create Date: 2026-07-21 07:53:48.417939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b387a98e7c25'
down_revision: Union[str, None] = 'a5d517fe8bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datasources_id', table_name='datasources')
    op.drop_index('ix_datasources_name', table_name='datasources')
    op.drop_table('datasources')
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('appearance', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notify_report_success', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_report_failed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password_set', sa.Boolean(), nullable=True))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'password_set')
    op.drop_column('users', 'notify_report_failed')
    op.drop_column('users', 'notify_report_success')
    op.drop_column('users', 'appearance')
    op.drop_column('users', 'language')
    op.create_table('datasources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('records_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='datasources_pkey')
    )
    op.create_index('ix_datasources_name', 'datasources', ['name'], unique=True)
    op.create_index('ix_datasources_id', 'datasources', ['id'], unique=False)
    # ### end Alembic commands ###
