"""add header_title, header_subtitle, theme_color, domain_type columns

Revision ID: b67023e3a96c
Revises: c0352238c842
Create Date: 2026-08-02 15:37:05.063841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67023e3a96c'
down_revision: Union[str, None] = 'c0352238c842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('header_title', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('header_subtitle', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('theme_color', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('domain_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'domain_type')
    op.drop_column('reports', 'theme_color')
    op.drop_column('reports', 'header_subtitle')
    op.drop_column('reports', 'header_title')
    # ### end Alembic commands ###
