"""add included_sections column

Revision ID: bd1a5ef568d9
Revises: 9b5ac6fe9a4a
Create Date: 2026-07-25 14:26:12.443296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1a5ef568d9'
down_revision: Union[str, None] = '9b5ac6fe9a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('included_sections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'included_sections')
    # ### end Alembic commands ###
