"""add total_file_size_bytes column

Revision ID: c0352238c842
Revises: ea80d96bfde7
Create Date: 2026-07-27 15:45:10.301090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0352238c842'
down_revision: Union[str, None] = 'ea80d96bfde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('total_file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'total_file_size_bytes')
    # ### end Alembic commands ###
