"""add tone and default_level columns

Revision ID: c6d6a72f0378
Revises: b67023e3a96c
Create Date: 2026-08-03 14:25:05.138349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d6a72f0378'
down_revision: Union[str, None] = 'b67023e3a96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('default_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'default_level')
    op.drop_column('reports', 'tone')
    # ### end Alembic commands ###
