"""add parsed_data_path column

Revision ID: ea80d96bfde7
Revises: a82afa3f5122
Create Date: 2026-07-27 09:06:00.368227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea80d96bfde7'
down_revision: Union[str, None] = 'a82afa3f5122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('parsed_data_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'parsed_data_path')
    # ### end Alembic commands ###
